In [3]:
import pandas as pd

In [8]:
#Create dataframe use python list 
information = [["karan",99],["priya",78],["jack",56],["mik",88]]
df = pd.DataFrame(information,columns=["Name","Marks"])
df

    Name  Marks
0  karan     99
1  priya     78
2   jack     56
3    mik     88

In [18]:
#Create data frame and use list and dictionery
employe_data = {
    "Name":["Rahul","Ruhanika","Jack","Michael"],
    "Department":["Ai-ml","Data-science","Business-analysis","Python-devlopar"],
    "Salary":[90000,87000,56000,54000],
}
df = pd.DataFrame(employe_data,index=[101,102,103,104])
df

         Name         Department  Salary
101     Rahul              Ai-ml   90000
102  Ruhanika       Data-science   87000
103      Jack  Business-analysis   56000
104   Michael    Python-devlopar   54000

In [20]:
#read json 
df = pd.read_json("data.json.txt")
print(df)

     Name  Age                Clg_name
0   karan   21  Gandhinagar_university
1  Shreya   20  Gandhinagar_university

#read excel file 
#chack (head,tail,info,describe,columns,shape)

In [24]:
excel_data = pd.read_excel(r"C:\Users\Ridhi Rathore\Downloads\Amazon_Sales_Dashboard_Practice.xlsx")
excel_data

,Order_ID,Order_Date,Customer,State,City,Category,Product,Quantity,Unit_Price,Sales,Profit,Payment_Method,Delivery_Status
0,1001,11-06-2025,Sneha,Gujarat,Surat,Books,Python Book,2,800,1600,192,UPI,Returned
1,1002,27-03-2025,Aarav,Rajasthan,Jaipur,Fashion,Jacket,4,4000,16000,2400,Credit Card,Cancelled
2,1003,06-03-2025,Sneha,Rajasthan,Jaipur,Fashion,Jacket,2,4000,8000,1280,Cash on Delivery,Delivered
3,1004,23-03-2025,Karan,Delhi,New Delhi,Electronics,iPhone,5,70000,350000,38500,Cash on Delivery,Shipped
4,1005,22-05-2025,Vivaan,Maharashtra,Mumbai,Electronics,Samsung S24,4,60000,240000,33600,Debit Card,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,1146,13-06-2025,Karan,Delhi,New Delhi,Electronics,Laptop,5,55000,275000,27500,Cash on Delivery,Cancelled
146,1147,26-05-2025,Karan,Delhi,New Delhi,Books,Python Book,2,800,1600,272,Debit Card,Returned
147,1148,01-04-2025,Rahul,Delhi,New Delhi,Electronics,Samsung S24,5,60000,300000,51000,UPI,Returned
148,1149,21-03-2025,Priya,Maharashtra,Mumbai,Electronics,Laptop,1,55000,55000,6050,Debit Card,Shipped
149,1150,04-01-2025,Rahul,Delhi,New Delhi,Home,Mixer,1,3500,3500,525,Debit Card,Delivered

In [25]:
excel_data.head()

,Order_ID,Order_Date,Customer,State,City,Category,Product,Quantity,Unit_Price,Sales,Profit,Payment_Method,Delivery_Status
0,1001,11-06-2025,Sneha,Gujarat,Surat,Books,Python Book,2,800,1600,192,UPI,Returned
1,1002,27-03-2025,Aarav,Rajasthan,Jaipur,Fashion,Jacket,4,4000,16000,2400,Credit Card,Cancelled
2,1003,06-03-2025,Sneha,Rajasthan,Jaipur,Fashion,Jacket,2,4000,8000,1280,Cash on Delivery,Delivered
3,1004,23-03-2025,Karan,Delhi,New Delhi,Electronics,iPhone,5,70000,350000,38500,Cash on Delivery,Shipped
4,1005,22-05-2025,Vivaan,Maharashtra,Mumbai,Electronics,Samsung S24,4,60000,240000,33600,Debit Card,Cancelled

In [26]:
excel_data.tail()

,Order_ID,Order_Date,Customer,State,City,Category,Product,Quantity,Unit_Price,Sales,Profit,Payment_Method,Delivery_Status
145,1146,13-06-2025,Karan,Delhi,New Delhi,Electronics,Laptop,5,55000,275000,27500,Cash on Delivery,Cancelled
146,1147,26-05-2025,Karan,Delhi,New Delhi,Books,Python Book,2,800,1600,272,Debit Card,Returned
147,1148,01-04-2025,Rahul,Delhi,New Delhi,Electronics,Samsung S24,5,60000,300000,51000,UPI,Returned
148,1149,21-03-2025,Priya,Maharashtra,Mumbai,Electronics,Laptop,1,55000,55000,6050,Debit Card,Shipped
149,1150,04-01-2025,Rahul,Delhi,New Delhi,Home,Mixer,1,3500,3500,525,Debit Card,Delivered

In [27]:
excel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         150 non-null    int64
 1   Order_Date       150 non-null    object
 2   Customer         150 non-null    object
 3   State            150 non-null    object
 4   City             150 non-null    object
 5   Category         150 non-null    object
 6   Product          150 non-null    object
 7   Quantity         150 non-null    int64
 8   Unit_Price       150 non-null    int64
 9   Sales            150 non-null    int64
 10  Profit           150 non-null    int64
 11  Payment_Method   150 non-null    object
 12  Delivery_Status  150 non-null    object
dtypes: int64(5), object(8)
memory usage: 15.4+ KB

In [28]:
#Chack and count null value 
excel_data.isnull().sum()  #No nun(mising value )value

Order_ID           0
Order_Date         0
Customer           0
State              0
City               0
Category           0
Product            0
Quantity           0
Unit_Price         0
Sales              0
Profit             0
Payment_Method     0
Delivery_Status    0
dtype: int64

In [29]:
excel_data.describe()

          Order_ID    Quantity    Unit_Price          Sales        Profit
count   150.000000  150.000000    150.000000     150.000000    150.000000
mean   1075.500000    3.053333  16604.666667   52960.666667   7342.253333
std      43.445368    1.527320  24844.633565   94275.012273  13532.353872
min    1001.000000    1.000000    650.000000     650.000000     52.000000
25%    1038.250000    2.000000    800.000000    3250.000000    422.750000
50%    1075.500000    3.000000   3500.000000   10000.000000   1270.000000
75%    1112.750000    5.000000   9000.000000   36000.000000   4312.500000
max    1150.000000    5.000000  70000.000000  350000.000000  59500.000000

In [30]:
excel_data.columns

Index(['Order_ID', 'Order_Date', 'Customer', 'State', 'City', 'Category',
       'Product', 'Quantity', 'Unit_Price', 'Sales', 'Profit',
       'Payment_Method', 'Delivery_Status'],
      dtype='object')

In [31]:
excel_data.shape

(150, 13)

Read CSV file 
And chack EDA(Exploratory Data Analysis)

In [5]:
Netflix_data = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\NetFlix.csv.zip")

In [34]:
#Chack first 5 rows
Netflix_data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

In [35]:
#Chack last 5 rows
Netflix_data.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
7782,s995,TV Show,Blown Away,NaN,NaN,Canada,12-Jul-19,2019,TV-14,1,"International TV Shows, Reality TV",Ten master artists turn up the heat in glassbl...
7783,s996,TV Show,Blue Exorcist,NaN,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Japan,1-Sep-20,2017,TV-MA,2,"Anime Series, International TV Shows",Determined to throw off the curse of being Sat...
7784,s997,Movie,Blue Is the Warmest Color,Abdellatif Kechiche,"Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...","France, Belgium, Spain",26-Aug-16,2013,NC-17,180,"Dramas, Independent Movies, International Movies","Determined to fall in love, 15-year-old Adele ..."
7785,s998,Movie,Blue Jasmine,Woody Allen,"Cate Blanchett, Sally Hawkins, Alec Baldwin, L...",United States,8-Mar-19,2013,PG-13,98,"Comedies, Dramas, Independent Movies",The high life leads to high anxiety for a fash...
7786,s999,Movie,Blue Jay,Alex Lehmann,"Sarah Paulson, Mark Duplass, Clu Gulager",United States,6-Dec-16,2016,TV-MA,81,"Dramas, Independent Movies, Romantic Movies",Two former high school sweethearts unexpectedl...

In [36]:
#Chack information of data
Netflix_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

In [38]:
#Chack and count nun value 
Netflix_data.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

In [39]:
#Chack describe
Netflix_data.describe()

       release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [42]:
#Chack columns name 
Netflix_data.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genres', 'description'],
      dtype='object')

In [46]:
#Chack data shape
Netflix_data.shape

(7787, 12)

In [6]:
#Chack size
Netflix_data.size

93444

In [8]:
#Only practice csv and use EDA(Exploratory data analysis)
df = pd.read_csv(r"C:\Users\Ridhi Rathore\Downloads\Iris.csv")

In [9]:
#Chack top 5 rows
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
#Chack last 5 rows 
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [11]:
#Chack information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [12]:
#Chack describe
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [13]:
#Chack columns
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [14]:
#chack shape 
df.shape

(150, 6)

In [15]:
#Chack total null value
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64